
struct SaveAd {
	ad_id: String,
	account_id: String,
	goods_type: Option<String>,
	category: String,
	product_type: Option<String>,
	technic: Option<String>,
	spare_part_type: Option<String>,
	technic_spare_part_type: Option<String>,
	make: Option<String>,
	availability: Option<String>,
	ad_type: Option<String>,
	condition: Option<String>,
	originality: Option<String>,
	original_oem: Option<String>,
	oem: Option<String>,
	price: Option<i32>,
	price_with_vat: Option<String>,
	// image_urls: Option<String>,
	video_url: Option<String>,
	video_file_url: Option<String>,
	contact_phone: Option<String>,
	internet_calls: Option<String>,
	manager_name: Option<String>,
	brand: Option<String>,
	weight_for_delivery: Option<f64>,
	height_for_delivery: Option<i32>,
	width_for_delivery: Option<i32>,
	length_for_delivery: Option<i32>,
	// delivery_options: Option<String>,
	multi_item: Option<String>,
	address: Option<String>,
	title: String,
	description: Option<String>,
}
